--CREAZIONE DEGLI UTENTI
CREATE USER AMMINISTRATORE_MSTR IDENTIFIED BY adm_mstr;
CREATE USER VISITATORE_MSTR IDENTIFIED BY vstr_mstr;
CREATE USER ESPOSITORE_MSTR IDENTIFIED BY espo_mstr;
CREATE USER ARTISTA_MSTR IDENTIFIED BY artst_mstr;
CREATE USER RESPONSABILE_LAVORATORI_SOCIETA IDENTIFIED BY societa_mstr;
CREATE USER RESPONSABILE_LAVORATORI_STAND IDENTIFIED BY stand_mstr;
CREATE USER REVISORE_CONTRATTI IDENTIFIED BY rev_contr;
CREATE USER RESPONSABILE_STAND IDENTIFIED BY resp_stand;
CREATE USER RESPONSABILE_BILANCIO IDENTIFIED BY resp_bil;
CREATE USER RESPONSABILE_VISITATORI IDENTIFIED BY resp_bigl;

GRANT ALL PRIVILEGES TO AMMINISTRATORE_MSTR;

--PERMESSI SULLE VISTE
GRANT SELECT MOSTRA_SPETTACOLI TO VISITATORE_MSTR;
GRANT SELECT MOSTRA_SPETTACOLI TO ARTISTA_MSTR;
GRANT SELECT MOSTRA_ESPOSITORI TO ESPOSITORE_MSTR;
GRANT SELECT MOSTRA_LAVORATORI_SOCIETA TO RESPONSABILE_LAVORATORI_SOCIETA;
GRANT SELECT MOSTRA_LAVORATORI_STAND TO RESPONSABILE_LAVORATORI_STAND;
GRANT SELECT MOSTRA_CONTRATTI_STIPULATI TO REVISORE_CONTRATTI;

--PERMESSI FUNCTION E STORED PROCEDURES
GRANT EXECUTE ON PROCEDURE SCONTO_MINORI TO RESPONSABILE_VISITATORI;
GRANT EXECUTE ON FUNCTION tuttelespese TO RESPONSABILE_BILANCIO;
GRANT EXECUTE ON FUNCTION tutteleentrate TO RESPONSABILE_BILANCIO;
GRANT EXECUTE ON FUNCTION BILANCIO TO RESPONSABILE_BILANCIO;
GRANT EXECUTE ON PROCEDURE BLOCCA_STAND TO RESPONSABILE_STAND;