/*SCHEDULER PER LA CANCELLAZIONE DELLE INFORMAZIONI SUGLI INGRESSI EFFETTUATI ALLA MOSTRA
OGNI GIORNO VENGONO ELIMINATI GLI INGRESSI EFFETTUATI IL GIORNO PRECEDENTE.
LO SCHEDULER INIZIA IL SUO LAVORO IL SECONDO GIORNO DELLA MOSTRA (28-04-2022), IN MODO DA CANCELLARE GLI INGRESSI EFFETTUATI IL PRIMO GIORNO (27-04-2022).
LO SCHEDULER TERMINA IL SUO LAVORO IL GIORNO 01-05-2022 IN MODO DA ELIMINARE GLI INGRESSI EFFETTUATI L’ULTIMO GIORNO DELLA MOSTRA (30-04-2022).
*/
BEGIN 
DBMS_SCHEDULER.CREATE_JOB(
    job_name     =>     'DeleteIngressiVisitatori',
    job_type     =>     'PLSQL_BLOCK',
    job_action   =>     'BEGIN
                            DELETE FROM Ingresso_Mostra
                            WHERE Data_Ora_Ingresso_Mostra<SYSDATE-1;
                        END;',
    start_date   =>     TO_DATE('28-04-2022','DD-MM-YYYY'),
    repeat_interval => 'FREQ=DAILY',
    end_date     =>     TO_DATE('01-05-2022','DD-MM-YYYY'),
    enabled     => TRUE,
    comments => 'CANCELLAZIONE INGRESSI VISITATORI GIORNO PRECEDENTE');
    END;

/*PER LA CANCELLAZIONE DEL JOB

    BEGIN
    DBMS_SCHEDULER.DROP_JOB('EliminaVisitatori');
    END;

*/